UWPCE-PythonCert-ClassRepos/Wi2018-Online

- students/rriehle/00-README.md
- students/rriehle/name_of_exercise/demo_file.py
> demo pull request

- students/marc_charbo/README.md
> marc charbo student folder

- students/Kenneth_Murray/README.md
> Kens first Commit for PyClass

- students/david_russo/README.rst
Adding my readme file; first attempt at collaboration
> Added a readme file

- students/PhongT/README.md
> initial commit

- students/Kenneth_Murray/Lesson1/break_me.py
> KenM Lesson1 BreakMe Script

- students/daniel_grubbs/README.md
- students/daniel_grubbs/lesson01/break_me.py
- Created my directory under student
- Created a README.md file
- Created a lesson01 directory and a simple Python file
> Added my student directory with README and simple file

- students/marc_charbo/lesson01/break_me.py
Error handling for NameError, TypeError, SyntaxError, AttributeError
> error handling on NameError, TypeError, SyntaxError, AttributeError

- students/GioSV/README.rst
- students/GioSV/mailroom/mailroom.py
Hello everyone,
I've started my first steps on Github, besides of setting my environment for Python.
I will continue submitting the assigned homework.
Regards,
GioSV
> Greetings, Professors! Lesson 1 Wi2018 Online

- students/Gabe_Lamberth/lesson02/FizzBuzz.py
- students/Gabe_Lamberth/lesson02/series.py
Finished lesson 02 assignments FizzBuzz & Series.py files. If there is any feedback, please let me know. I'm still working on the Grid printer.
> adding FizzBuzz & series files

- students/Sam_Cooper/README.rst
- students/Sam_Cooper/lesson01/break_me.py
Added a new line in the README file for testing purposes.
> Appended revised version of README

- students/Gabe_Lamberth/lesson02/grid_printer.py
still working to add row, col function. This program will run only with single vaule
> Adding unfinished grid printer w/o part 3

- students/darrell_h/lesson_2/fizz_buzz.py
- students/darrell_h/lesson_2/grid_printer.py
- students/darrell_h/lesson_2/series.py
I'd appreciate any feedback on the series and grid solutions.  They work but I am interested to know if I could have been more concise.
> Lesson 2 Assignment

- students/david_russo/lesson2/drawing_grids.py
- students/david_russo/lesson2/fizzbuzz.py
- students/david_russo/lesson2/series.py
Hi, I am submitting my homework for lesson02 as a pull request.
> David Russo lesson02 pull request 

- students/Gabe_Lamberth/lesson02/grid_printer.py
per instructor comments removed functions for text and added global variables  and cleaned up for loop for readability
> updated finished grid printer

- students/chaycasso/Lesson02/fizzbuzz.py
- students/chaycasso/Lesson02/gridprinter.py
- students/chaycasso/Lesson02/series.py
- students/chaycasso/Lesson03/slicing.py
- students/chaycasso/README.md
Lesson 2 Pull Request for all 3 exercises.
> Lesson 2 Pull Request.

- students/Zhengtang_Yang/FizzBuzzExercise.py
- students/Zhengtang_Yang/GridPrinterExercise.py
- students/Zhengtang_Yang/Lesson02/series.py
- students/Zhengtang_Yang/Lesson03/SlicingLabExercise.py
- students/Zhengtang_Yang/Lesson03/list_lab.py
Please take a look at my Series.py. Thanks a lot!
> Added Series.py

- students/Gabe_Lamberth/lesson03/Sequence.py
- students/Gabe_Lamberth/lesson03/list_lab.py
adding lesson 03 assignment 1 for slice sequencing
> add in lesson 03 slice sequencing

- students/ScottL/lesson03/lists.py
- students/ScottL/lesson03/mailroom.py
- students/ScottL/lesson03/slicing.py
- students/ScottL/lesson03/strformat_lab.py
> ScottL lesson03

- students/Sam_Cooper/lesson02/fizzbuzz.py
Adding fizzbuzz.py for Fizz Buzz grade submission.
> Adding additional lesson02 programs

- students/daniel_grubbs/lesson04/dict_lab.py
- students/daniel_grubbs/lesson04/file_lab.py
- students/daniel_grubbs/lesson04/kata_fourteen.py
- students/daniel_grubbs/lesson04/mailroom2.py
- students/daniel_grubbs/lesson04/some_file.txt
- students/daniel_grubbs/lesson05/except_exercise.py
- students/daniel_grubbs/lesson05/except_test.py
- students/daniel_grubbs/lesson05/mailroom3.py
- Placed in the correct version on the mailroom app
> Updated mailroom2.py in lesson04

- students/darrell_h/lesson_4/file_handling.py
- students/darrell_h/lesson_4/mailroom_enhanced.py
- students/darrell_h/lesson_4/sherlock.txt
- students/darrell_h/lesson_4/sherlock_small.txt
- students/darrell_h/lesson_4/test.txt
- students/darrell_h/lesson_4/tom_swift_and_his_airship_ch1.txt
- students/darrell_h/lesson_4/trigrams.py
- students/darrell_h/lesson_5/except_exercise.py
- students/darrell_h/lesson_5/except_test.py
- students/darrell_h/lesson_5/mailroom_with_exceptions.py
Struggled with the tigram assignment.  only managed to create a list without punctuation / whitespace and digits.  Could not figure out how to iterate through the new list searching for 2x adj values and extracting 3rd value.  Waaaayyy to complex for my brain.. 👎 :-)
@rriehle maybe we can go over this tomorrow?
cheers.
> Lesson 4 assignments and exception handling from lesson 5

- students/ssankura/README.rst
- students/ssankura/lesson01/break_me.py
- students/ssankura/lesson02/fizzbuzz.py
- students/ssankura/lesson02/gridprinter.py
- students/ssankura/lesson02/series.py
- students/ssankura/test.txt
My ID - ssankura - is an alias for Sireesha Sankuratripati
Created my student folder with the name "ssankura" - added a Readme file
Created a folder lesson01 in my student folder(ssankura) - added break_me.py file
Added lesson02 - assignment1 - grid printer functionality, filename: gridprinter.py
added lesson02 - assignment2 - fizz buzz functionality, filename: fizzbuzz.py
added lesson02 - assignment3 - sum series (fibonacci and lucas): series.py
changed code for series.py to use non-recursive approach to compute the fibonacci and lucas values
> Lesson01 and Lesson02 submission

- .idea/vcs.xml
- students/Gabe_Lamberth/lesson03/mailroom.py
- students/Gabe_Lamberth/lesson04/dict_lab.py
Using the f-string was nice. Tuesday's session about the f-string formatting helped alot.
> adding completed mailroom assignment3 lab

- students/John_Sekora/lesson01/break_me.py
- students/John_Sekora/lesson01/coding_bat.py
- students/John_Sekora/lesson02/fibonacci.py
- students/John_Sekora/lesson02/fizzbuzz.py
- students/John_Sekora/lesson02/grid_printer.py
- students/John_Sekora/lesson03/Slicing_Lab.py
- students/John_Sekora/lesson03/list_lab.py
- students/John_Sekora/lesson03/mailroom.py
- students/John_Sekora/lesson03/strformat_lab.py
This is my first pull request!
> Assignments for lesson01 - lesson03

- students/ssankura/README.rst
- students/ssankura/lesson01/break_me.py
- students/ssankura/lesson02/fizzbuzz.py
- students/ssankura/lesson02/gridprinter.py
- students/ssankura/lesson02/series.py
- students/ssankura/lesson03/slicing.py
- students/ssankura/test.txt
Lesson 03 - assignment 01 - slicing assignment submission
> Branch lesson03 - slicing.py and list_lab.py submission 

- students/chaycasso/Lesson05/except_exercise.py
- students/chaycasso/Lesson05/except_test.py
- students/chaycasso/Lesson05/mailroom3.py
Hello,
I couldn't find any comprehensions to add to Mailroom3, as I'm not building anything but the original donor table, whose format I think is more easily read. Please let me know if you see something I should correct.
Chay
> Lesson 05 commits.

- students/Aron/Module5/except_exercise.py
- students/Aron/Module5/except_test.py
- students/Aron/Module_2/FizzBuzz.py
- students/Aron/Module_2/FizzBuzz2.py
- students/Aron/Module_2/GridEx.py
- students/Aron/Module_2/grid_print2.py
- students/Aron/Module_2/series.py
- students/Aron/Module_2/seriestest.py
- students/Aron/Module_3/Lists.py
- students/Aron/Module_3/Mailroom.py
- students/Aron/Module_3/slicing.py
- students/Aron/Module_3/strformat_lab.py
- students/Aron/Module_4/Aronfinal.txt
- students/Aron/Module_4/Jeanfinal.txt
- students/Aron/Module_4/Joanfinal.txt
- students/Aron/Module_4/Mailroom.py
- students/Aron/Module_4/Mailroom_Mod4.py
- students/Aron/Module_4/Mailroom_Mod4_test.py
- students/Aron/Module_4/Mailroom_Mod4_v2.py
- students/Aron/Module_4/Scottfinal.txt
- students/Aron/Module_4/dict_lab.py
- students/Aron/Module_4/sherlock_small.txt
- students/Aron/Module_4/trigramkata.py
- students/Aron/Samples/samples.py
> Update of homework files

- students/Gabe_Lamberth/lesson04/Andres.txt
- students/Gabe_Lamberth/lesson04/Carolyn.txt
- students/Gabe_Lamberth/lesson04/Emma.txt
- students/Gabe_Lamberth/lesson04/file_lab.py
- students/Gabe_Lamberth/lesson04/mailroom2.py
I really liked using the pathlib library. Easier to read IMO
> Adding file_lab.py

- students/marc_charbo/lesson07/html_render.py
- students/marc_charbo/lesson07/run_html_render.py
- students/marc_charbo/lesson07/test_html_output1.html
- students/marc_charbo/lesson08/circle.py
- students/marc_charbo/lesson08/logging.conf
- students/marc_charbo/lesson08/test_circle.py
I don't understand the following error:
File "/Users/charbo/Documents/WU/Py1/Wi2018-Online/students/marc_charbo/lesson07/html_render.py", line 36, in render
self.content.append(TextWrapper(self.content))
AttributeError: 'str' object has no attribute 'append'
I understand that we have to modify render depending if we are passing an object from subclass or just a string. But i am lost on how to do it and on the error msg.
Thanks in advance for your help.
> stuck on q2

- .idea/vcs.xml
- students/Gabe_Lamberth/lesson05/except_exercise.py
- students/Gabe_Lamberth/lesson05/except_test.py
- students/Gabe_Lamberth/lesson05/mailroom3.py
- students/Gabe_Lamberth/lesson06/mailroom4.py
- students/Gabe_Lamberth/lesson06/mailroom_test.py
Wanted to also remove the vcs.xml from my fork. I accidentally created it through Pycharm. I don't know if it's in the repository, but in just in case.
> Completed lesson 5 projects

- students/ssankura/lesson03/list_lab.py
- students/ssankura/lesson03/mailroom.py
- students/ssankura/lesson03/strformat_lab.py
Added strformat_lab.py , list lab and mailroom.py
> Branch lesson03

- students/daniel_grubbs/lesson05/mailroom3.py
- students/daniel_grubbs/lesson06/mailroom4.py
- students/daniel_grubbs/lesson06/test_mailroom4.py
- students/daniel_grubbs/lesson07/html_render.py
- students/daniel_grubbs/lesson07/run_html_render.py
- students/daniel_grubbs/lesson07/test_html_output3.html
- students/daniel_grubbs/lesson07/test_html_render.py
- students/daniel_grubbs/lesson08/circle.py
- students/daniel_grubbs/lesson08/test_circle.py
- Continuing to work on html_render from Lesson 07 but partially complete 
- Done through step 3 of assignment
> Lesson 06 and partial Lesson 07 for html_render

- students/chaycasso/Lesson06/mailroom4.py
- students/chaycasso/Lesson06/test_mailroom.py
- students/chaycasso/Lesson07/html_render.py
- students/chaycasso/Lesson07/html_render_test.py
I believe that I've tested the code to the extent possible.
> Lesson 06 pull request.

- students/Preethi_Krishnan/lesson_02/fizz_buzz.py
- students/Preethi_Krishnan/lesson_02/series.py
- students/Preethi_Krishnan/lesson_03/list_lab.py
- students/Preethi_Krishnan/lesson_03/slicing.py
> Lesson 2 assignments

- students/PadmajaPeri/CircleClass/Circle.py
- students/PadmajaPeri/lesson03/mailroom.py
> Circle Class Assigment

- students/ssankura/lesson04/Jeff Bezos.txt
- students/ssankura/lesson04/Joanne K Rowling.txt
- students/ssankura/lesson04/Mark Zuckerberg.txt
- students/ssankura/lesson04/Paul Allen.txt
- students/ssankura/lesson04/dict_lab.py
- students/ssankura/lesson04/file_lab.py
- students/ssankura/lesson04/mailroom.py
Lesson04 - added mailroom.py
added labs for dictionary and file
added text files for the letters generated
> Lesson04 - mailroom.py and labs

- students/Gabe_Lamberth/lesson08/tst_circle.py
forgot to add circle class unit testing
> Circle class unit test

- students/Gabe_Lamberth/lesson09/mailroom5.py
- students/Gabe_Lamberth/lesson09/run_mailroom.py
adding assignment 9...not fully streamlined, but a good starting point.
> assignment 9

- students/Preethi_Krishnan/Exceptions_exercise/except_exercise.py
- students/Preethi_Krishnan/Exceptions_exercise/except_test.py
- students/Preethi_Krishnan/lesson_03/mail_room_1.py
- students/Preethi_Krishnan/lesson_03/string_format.py
- students/Preethi_Krishnan/lesson_04/mailroom_2.py
- students/Preethi_Krishnan/lesson_05/mailroom_3.py
- students/Preethi_Krishnan/lesson_06/mailroom_3.py
- students/Preethi_Krishnan/lesson_06/mailroom_4_unittest.py
Please provide feedback for exceptions exercise.
> Please review and provide feedback for exception exercise

- students/Kenneth_Murray/Lesson2/fizzbuzz/FizzBuzz.py
> Ken Murray Mailroom 1

- students/daniel_grubbs/lesson09/mailroom_oo.py
- students/daniel_grubbs/lesson09/test_mailroom_oo.py
- students/daniel_grubbs/lesson10/mailroom_fp.py
- students/daniel_grubbs/lesson10/test_mailroom_fp.py
- Have the program running using a Donor class with functionality for each menu item
- Have a few tests setup
> Mailroom object oriented assignment

- students/Preethi_Krishnan/lesson_06/mailroom_3.py
- students/Preethi_Krishnan/lesson_06/mailroom_4_unittest.py
- students/Preethi_Krishnan/lesson_08/circle.py
Please review and provide feedback for circle assignment. I have not invoked all the magic methods but for example put couple of them in main(). Please let me know if this is ok
> Please review and provide feedback for circle assignment

- students/marc_charbo/lesson09/Bob.txt
- students/marc_charbo/lesson09/Jim.txt
- students/marc_charbo/lesson09/Linda.txt
- students/marc_charbo/lesson09/MoneyMan.txt
- students/marc_charbo/lesson09/MoneyMan_test.txt
- students/marc_charbo/lesson09/donor.py
- students/marc_charbo/lesson09/donors_data.py
- students/marc_charbo/lesson09/logging.conf
- students/marc_charbo/lesson09/mailroom_v4_fp.py
- students/marc_charbo/lesson09/mailroom_v5_oo.py
- students/marc_charbo/lesson09/test_mailroom_v4_fp.py
- students/marc_charbo/lesson09/test_mailroom_v5_oo.py
Not sure how to test option 2, create report since it is printed on screen. Should I test components of report like correct avg amount?
Missing unit tests for send thank you, will add tomorrow.
> lesson09, code done some unit test missing

- students/Preethi_Krishnan/lesson_06/mailroom_4_unittest.py
- students/Preethi_Krishnan/lesson_09/mailroom_oo.py
Please review and provide feedback
> I have added some assertions to the unit test code. 

- students/ScottL/lesson10/mailroom_functional.py
New menu items 4 and 5 for functional code, map and filter
> ScottL lesson10, functional mailroom

- students/marc_charbo/lesson06/Jim_test.txt
- students/marc_charbo/lesson06/test_mailroom_v4.py
add more tests to lesson 06, all functions are now tested
> completed tests for lesson 06

- students/ssankura/lesson06/mailroom4.py
- students/ssankura/lesson06/test_mailroom4.py
refactored several methods in mailroom.py to enable testing separate functionalities
added test cases in separate file
> Lesson06 - added mailroom part 4 and test cases for mailroom

- students/ssankura/lesson08/circle.py
- students/ssankura/lesson08/test_circle.py
Implementation of Circle Class and testing the functionality in the __name__ == "__main__" section of code
> Lesson08 - Implementation of Circle Class - circle.py

- students/ssankura/lesson08/circle.py
- students/ssankura/lesson08/test_circle.py
- students/ssankura/lesson09/mailroom.py
- students/ssankura/lesson09/test_mailroom.py
Object oriented mailroom and the unit test cases
> Lesson09 - mailroom and unit test cases 
